ui:
    resource: "@UIBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /api/

export:
    resource: "@ExportBundle/Controller/"
    type:     annotation
    prefix:   /export