security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_API, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory: ~

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~

    access_control:
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }