services:
    user_service:
        class: AppBundle\Services\UserService
        arguments: ['@user_manager','@security.password_encoder']

    user_manager:
            class: AppBundle\Managers\UserManager
            arguments: ['@doctrine.orm.default_entity_manager']


    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
    app.exception_listener:
            class: AppBundle\Security\ExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception }