services:
    user_service:
        class: AppBundle\Services\UserService
        arguments: ['@user_manager','@security.password_encoder','@validator']
    user_manager:
          class: AppBundle\Managers\UserManager
          arguments: ['@doctrine.orm.default_entity_manager']

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
    app.exception_listener:
          class: AppBundle\Security\ExceptionListener
          tags:
              - { name: kernel.event_listener, event: kernel.exception }

    student_service:
        class: AppBundle\Services\StudentService
        arguments: ['@student_manager','@validator']
    student_manager:
        class: AppBundle\Managers\StudentManager
        arguments: ['@doctrine.orm.default_entity_manager']

    course_service:
            class: AppBundle\Services\CourseService
            arguments: ['@course_manager','@validator']
    course_manager:
            class: AppBundle\Managers\CourseManager
            arguments: ['@doctrine.orm.default_entity_manager']

    speciality_service:
            class: AppBundle\Services\SpecialityService
            arguments: ['@speciality_manager','@validator']
    speciality_manager:
            class: AppBundle\Managers\SpecialityManager
            arguments: ['@doctrine.orm.default_entity_manager']

    subject_service:
            class: AppBundle\Services\SubjectService
            arguments: ['@subject_manager', '@validator']
    subject_manager:
            class: AppBundle\Managers\SubjectManager
            arguments: ['@doctrine.orm.default_entity_manager']

    student_assessment_service:
            class: AppBundle\Services\StudentAssessmentService
            arguments: ['@student_assessment_manager', '@validator']
    student_assessment_manager:
            class: AppBundle\Managers\StudentAssessmentManager
            arguments: ['@doctrine.orm.default_entity_manager']